### ISSUE TITLE
Crash with Thaumcraft

### ISSUE THREAD

**Issue by mitchcbr** [kingrunes/Somnia#19]
I found a crash bug with Somnia Somnia-1.4.1.23 and Thaumcraft 1.7.10-4.2.3.5. I've been able to reproduce it in both Forge 10.13.2.1291 and 10.13.3.1401-1710ls. Removing Somnia from my mods list eliminates the crash.

How to reproduce:
1. Install Forge, Thaumcraft, and Somnia.
2. Start a new creative game.
3. Grab the Thaumonomicon from the items list.
4. Open the Thaumonomicon, leaving it on the initial tab.
5. Grab the page and move  your view toward the bottom-right.
6. Kersplatt.

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/7/15 9:28 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:176)
	at net.minecraft.tileentity.TileEntity.func_145828_a(TileEntity.java:223)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:105)
	at thaumcraft.client.renderers.block.BlockTableRenderer.renderInventoryBlock(BlockTableRenderer.java:37)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
	at FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:612)
	at thaumcraft.client.gui.GuiResearchBrowser.func_73863_a(GuiResearchBrowser.java:280)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:50)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:176)
	at net.minecraft.tileentity.TileEntity.func_145828_a(TileEntity.java:223)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:105)
	at thaumcraft.client.renderers.block.BlockTableRenderer.renderInventoryBlock(BlockTableRenderer.java:37)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderInventoryBlock(RenderingRegistry.java:125)
	at FMLRenderAccessLibrary.renderInventoryBlock(FMLRenderAccessLibrary.java:59)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8145)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)

-- Item being rendered --
Details:
	Item Type: thaumcraft.common.blocks.BlockTableItem@5f7a911f
	Item Aux: 14
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:612)
	at thaumcraft.client.gui.GuiResearchBrowser.func_73863_a(GuiResearchBrowser.java:280)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchBrowser
	Mouse location: Scaled: (256, 124). Absolute: (513, 230)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['ineluki12'/237, l='MpServer', x=-50.79, y=75.62, z=80.35]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 04 - OWG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 336685 game time, 336685 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
	Forced entities: 33 total; [EntityZombie['Zombie'/1728, l='MpServer', x=-79.41, y=59.00, z=9.95], EntityZombie['Zombie'/1730, l='MpServer', x=-69.50, y=59.00, z=10.50], EntityBat['Bat'/261, l='MpServer', x=20.71, y=50.74, z=53.38], EntityBat['Bat'/263, l='MpServer', x=26.75, y=42.00, z=71.63], EntityCreeper['Creeper'/1558, l='MpServer', x=-118.50, y=66.00, z=16.50], EntityZombie['Zombie'/1686, l='MpServer', x=-88.72, y=28.00, z=117.13], EntityCreeper['Creeper'/1559, l='MpServer', x=-113.50, y=66.00, z=15.50], EntitySkeleton['Skeleton'/1180, l='MpServer', x=-85.53, y=47.00, z=17.06], EntityCreeper['Creeper'/1630, l='MpServer', x=-84.97, y=48.00, z=11.50], EntityZombie['Zombie'/159, l='MpServer', x=-56.39, y=76.99, z=69.69], EntityZombie['Zombie'/160, l='MpServer', x=-44.91, y=77.00, z=66.50], EntityItem['item.item.rottenFlesh'/161, l='MpServer', x=-35.22, y=72.13, z=90.19], EntitySkeleton['Skeleton'/1509, l='MpServer', x=-91.50, y=28.00, z=118.50], EntityZombie['Zombie'/1191, l='MpServer', x=-77.50, y=59.00, z=20.50], EntityItem['item.item.rottenFlesh'/1959, l='MpServer', x=-32.72, y=71.13, z=93.78], EntityZombie['Zombie'/1192, l='MpServer', x=-76.50, y=59.00, z=20.50], EntityZombie['Zombie'/1193, l='MpServer', x=-77.50, y=59.00, z=19.50], EntitySkeleton['Skeleton'/1194, l='MpServer', x=-74.50, y=59.00, z=23.50], EntityZombie['Zombie'/1514, l='MpServer', x=-82.53, y=62.00, z=127.03], EntitySkeleton['Skeleton'/1580, l='MpServer', x=-94.50, y=38.00, z=108.25], EntityWitch['Witch'/1581, l='MpServer', x=-94.89, y=39.00, z=100.56], EntityWitch['Witch'/1582, l='MpServer', x=-94.63, y=38.00, z=102.50], EntityClientPlayerMP['ineluki12'/237, l='MpServer', x=-50.79, y=75.62, z=80.35], EntityWitch['Witch'/1583, l='MpServer', x=-91.53, y=38.00, z=96.95], EntityItem['item.item.arrow'/176, l='MpServer', x=-29.09, y=73.13, z=78.63], EntityWitch['Witch'/1584, l='MpServer', x=-99.50, y=38.00, z=104.50], EntityItem['item.item.bone'/177, l='MpServer', x=-29.81, y=71.13, z=80.41], EntityBat['Bat'/1146, l='MpServer', x=-84.30, y=35.00, z=94.81], EntityBat['Bat'/1147, l='MpServer', x=-85.60, y=35.01, z=94.41], EntityBat['Bat'/381, l='MpServer', x=-80.19, y=19.24, z=110.36], EntityBat['Bat'/382, l='MpServer', x=-97.89, y=20.00, z=112.36], EntityZombie['Zombie'/190, l='MpServer', x=22.90, y=80.00, z=153.38], EntityBat['Bat'/383, l='MpServer', x=-78.30, y=19.77, z=109.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404861136 bytes (386 MB) / 1264582656 bytes (1206 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 20 mods loaded, 20 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SomniaCore{1.3.1.23} [SomniaCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	smeltchevsky{b3} [Armor Smelter] (Armor-Smelter-Mod-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ObsidianBoat{v1.3.2} [Obsidian Boat] (ObsidianBoat-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OWG{1.0.3} [Old World Gen] (OWG-1.0.3-1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Somnia{-au} [Somnia] (Somnia-1.4.1.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 9.18.10.3220' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10-Forge10.13.3.1401-1710ls
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.0.0 - Build 9.18.10.3220, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by kingrunes** [comment]
Does this crash still occur with the patched version for 1.7.10 from the mc forum thread? 
https://dl.dropboxusercontent.com/u/2781986/Somnia/Somnia-1.4.3.1.jar
